# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'climate_control/display/mainwindow.ui'
#
# Created: Thu Jun 25 16:29:03 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_DisplayMainWindow(object):
    def setupUi(self, DisplayMainWindow):
        DisplayMainWindow.setObjectName("DisplayMainWindow")
        DisplayMainWindow.resize(1024, 700)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DisplayMainWindow.sizePolicy().hasHeightForWidth())
        DisplayMainWindow.setSizePolicy(sizePolicy)
        DisplayMainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        DisplayMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DisplayMainWindow.setWindowIcon(icon)
        DisplayMainWindow.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(DisplayMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.screen_label = QtGui.QLabel(self.centralwidget)
        self.screen_label.setGeometry(QtCore.QRect(0, -2, 1024, 80))
        self.screen_label.setText("")
        self.screen_label.setPixmap(QtGui.QPixmap(":/images/banner.png"))
        self.screen_label.setObjectName("screen_label")
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 1011, 592))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tabWidget = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(764, 590))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.temperature_tab = QtGui.QWidget()
        self.temperature_tab.setObjectName("temperature_tab")
        self.layoutWidget1 = QtGui.QWidget(self.temperature_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(110, 10, 621, 28))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.temperature_threshold_label_tab = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.temperature_threshold_label_tab.setFont(font)
        self.temperature_threshold_label_tab.setObjectName("temperature_threshold_label_tab")
        self.horizontalLayout_2.addWidget(self.temperature_threshold_label_tab)
        self.temperature_threshold = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.temperature_threshold.setFont(font)
        self.temperature_threshold.setText("")
        self.temperature_threshold.setScaledContents(True)
        self.temperature_threshold.setObjectName("temperature_threshold")
        self.horizontalLayout_2.addWidget(self.temperature_threshold)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.temperature_label_tab = QtGui.QLabel(self.layoutWidget1)
        self.temperature_label_tab.setMinimumSize(QtCore.QSize(73, 20))
        self.temperature_label_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.temperature_label_tab.setSizeIncrement(QtCore.QSize(0, 0))
        self.temperature_label_tab.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.temperature_label_tab.setFont(font)
        self.temperature_label_tab.setTextFormat(QtCore.Qt.AutoText)
        self.temperature_label_tab.setScaledContents(True)
        self.temperature_label_tab.setObjectName("temperature_label_tab")
        self.horizontalLayout.addWidget(self.temperature_label_tab)
        self.temperature_value = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.temperature_value.setFont(font)
        self.temperature_value.setText("")
        self.temperature_value.setScaledContents(True)
        self.temperature_value.setObjectName("temperature_value")
        self.horizontalLayout.addWidget(self.temperature_value)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.temperature_tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 40, 751, 511))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.graph_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.graph_layout.setContentsMargins(0, 0, 0, 0)
        self.graph_layout.setObjectName("graph_layout")
        self.tabWidget.addTab(self.temperature_tab, "")
        self.humidity_tab = QtGui.QWidget()
        self.humidity_tab.setObjectName("humidity_tab")
        self.layoutWidget_2 = QtGui.QWidget(self.humidity_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(110, 10, 621, 28))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.humidity_threshold_label_tab = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setWeight(50)
        font.setBold(False)
        self.humidity_threshold_label_tab.setFont(font)
        self.humidity_threshold_label_tab.setScaledContents(True)
        self.humidity_threshold_label_tab.setObjectName("humidity_threshold_label_tab")
        self.horizontalLayout_8.addWidget(self.humidity_threshold_label_tab)
        self.humidity_threshold = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.humidity_threshold.setFont(font)
        self.humidity_threshold.setText("")
        self.humidity_threshold.setScaledContents(True)
        self.humidity_threshold.setObjectName("humidity_threshold")
        self.horizontalLayout_8.addWidget(self.humidity_threshold)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.humidity_label_tab = QtGui.QLabel(self.layoutWidget_2)
        self.humidity_label_tab.setMinimumSize(QtCore.QSize(73, 20))
        self.humidity_label_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.humidity_label_tab.setSizeIncrement(QtCore.QSize(0, 0))
        self.humidity_label_tab.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.humidity_label_tab.setFont(font)
        self.humidity_label_tab.setTextFormat(QtCore.Qt.AutoText)
        self.humidity_label_tab.setScaledContents(True)
        self.humidity_label_tab.setObjectName("humidity_label_tab")
        self.horizontalLayout_9.addWidget(self.humidity_label_tab)
        self.humidity_value = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.humidity_value.setFont(font)
        self.humidity_value.setText("")
        self.humidity_value.setScaledContents(True)
        self.humidity_value.setObjectName("humidity_value")
        self.horizontalLayout_9.addWidget(self.humidity_value)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.humidity_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 40, 761, 511))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.humidity_graph_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.humidity_graph_layout.setContentsMargins(0, 0, 0, 0)
        self.humidity_graph_layout.setObjectName("humidity_graph_layout")
        self.tabWidget.addTab(self.humidity_tab, "")
        self.horizontalLayout_10.addWidget(self.tabWidget)
        spacerItem4 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem5 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem5)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame1 = QtGui.QFrame(self.frame)
        self.frame1.setFrameShape(QtGui.QFrame.Box)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.connection_status_label = QtGui.QLabel(self.frame1)
        self.connection_status_label.setMinimumSize(QtCore.QSize(73, 20))
        self.connection_status_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.connection_status_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.connection_status_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.connection_status_label.setFont(font)
        self.connection_status_label.setStyleSheet("")
        self.connection_status_label.setTextFormat(QtCore.Qt.AutoText)
        self.connection_status_label.setScaledContents(True)
        self.connection_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.connection_status_label.setObjectName("connection_status_label")
        self.verticalLayout_4.addWidget(self.connection_status_label)
        self.connection_status = QtGui.QLabel(self.frame1)
        self.connection_status.setMinimumSize(QtCore.QSize(73, 20))
        self.connection_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.connection_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.connection_status.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.connection_status.setFont(font)
        self.connection_status.setStyleSheet("color: rgb(42, 126, 70);")
        self.connection_status.setTextFormat(QtCore.Qt.AutoText)
        self.connection_status.setScaledContents(True)
        self.connection_status.setAlignment(QtCore.Qt.AlignCenter)
        self.connection_status.setWordWrap(True)
        self.connection_status.setObjectName("connection_status")
        self.verticalLayout_4.addWidget(self.connection_status)
        self.verticalLayout_8.addWidget(self.frame1)
        self.frame2 = QtGui.QFrame(self.frame)
        self.frame2.setFrameShape(QtGui.QFrame.Box)
        self.frame2.setObjectName("frame2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.latency_label = QtGui.QLabel(self.frame2)
        self.latency_label.setMinimumSize(QtCore.QSize(73, 20))
        self.latency_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.latency_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.latency_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.latency_label.setFont(font)
        self.latency_label.setTextFormat(QtCore.Qt.AutoText)
        self.latency_label.setScaledContents(True)
        self.latency_label.setAlignment(QtCore.Qt.AlignCenter)
        self.latency_label.setObjectName("latency_label")
        self.verticalLayout_7.addWidget(self.latency_label)
        self.latency = QtGui.QLabel(self.frame2)
        self.latency.setMinimumSize(QtCore.QSize(73, 20))
        self.latency.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.latency.setSizeIncrement(QtCore.QSize(0, 0))
        self.latency.setBaseSize(QtCore.QSize(11, 0))
        self.latency.setTextFormat(QtCore.Qt.AutoText)
        self.latency.setScaledContents(True)
        self.latency.setAlignment(QtCore.Qt.AlignCenter)
        self.latency.setObjectName("latency")
        self.verticalLayout_7.addWidget(self.latency)
        self.verticalLayout_8.addWidget(self.frame2)
        self.verticalLayout_9.addWidget(self.frame)
        spacerItem6 = QtGui.QSpacerItem(185, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem6)
        self.frame_2 = QtGui.QFrame(self.layoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.controller_label = QtGui.QLabel(self.frame_2)
        self.controller_label.setMinimumSize(QtCore.QSize(94, 20))
        self.controller_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controller_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.controller_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.controller_label.setFont(font)
        self.controller_label.setTextFormat(QtCore.Qt.AutoText)
        self.controller_label.setScaledContents(True)
        self.controller_label.setObjectName("controller_label")
        self.verticalLayout_2.addWidget(self.controller_label)
        self.sensor_label = QtGui.QLabel(self.frame_2)
        self.sensor_label.setMinimumSize(QtCore.QSize(73, 20))
        self.sensor_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensor_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.sensor_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.sensor_label.setFont(font)
        self.sensor_label.setTextFormat(QtCore.Qt.AutoText)
        self.sensor_label.setScaledContents(True)
        self.sensor_label.setObjectName("sensor_label")
        self.verticalLayout_2.addWidget(self.sensor_label)
        self.actuator_label = QtGui.QLabel(self.frame_2)
        self.actuator_label.setMinimumSize(QtCore.QSize(73, 20))
        self.actuator_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.actuator_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.actuator_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.actuator_label.setFont(font)
        self.actuator_label.setTextFormat(QtCore.Qt.AutoText)
        self.actuator_label.setScaledContents(True)
        self.actuator_label.setObjectName("actuator_label")
        self.verticalLayout_2.addWidget(self.actuator_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.controller_status = QtGui.QLabel(self.frame_2)
        self.controller_status.setMinimumSize(QtCore.QSize(73, 20))
        self.controller_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.controller_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.controller_status.setBaseSize(QtCore.QSize(11, 0))
        self.controller_status.setTextFormat(QtCore.Qt.AutoText)
        self.controller_status.setScaledContents(True)
        self.controller_status.setObjectName("controller_status")
        self.verticalLayout.addWidget(self.controller_status)
        self.sensor_status = QtGui.QLabel(self.frame_2)
        self.sensor_status.setMinimumSize(QtCore.QSize(73, 20))
        self.sensor_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensor_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.sensor_status.setBaseSize(QtCore.QSize(11, 0))
        self.sensor_status.setTextFormat(QtCore.Qt.AutoText)
        self.sensor_status.setScaledContents(True)
        self.sensor_status.setObjectName("sensor_status")
        self.verticalLayout.addWidget(self.sensor_status)
        self.actuator_status = QtGui.QLabel(self.frame_2)
        self.actuator_status.setMinimumSize(QtCore.QSize(73, 20))
        self.actuator_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.actuator_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.actuator_status.setBaseSize(QtCore.QSize(11, 0))
        self.actuator_status.setTextFormat(QtCore.Qt.AutoText)
        self.actuator_status.setScaledContents(True)
        self.actuator_status.setObjectName("actuator_status")
        self.verticalLayout.addWidget(self.actuator_status)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_9.addWidget(self.frame_2)
        spacerItem7 = QtGui.QSpacerItem(197, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_9.addItem(spacerItem7)
        self.frame3 = QtGui.QFrame(self.layoutWidget)
        self.frame3.setFrameShape(QtGui.QFrame.Box)
        self.frame3.setObjectName("frame3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame4 = QtGui.QFrame(self.frame3)
        self.frame4.setFrameShape(QtGui.QFrame.Box)
        self.frame4.setObjectName("frame4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.heater_status_label = QtGui.QLabel(self.frame4)
        self.heater_status_label.setMinimumSize(QtCore.QSize(73, 20))
        self.heater_status_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heater_status_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.heater_status_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.heater_status_label.setFont(font)
        self.heater_status_label.setStyleSheet("")
        self.heater_status_label.setTextFormat(QtCore.Qt.AutoText)
        self.heater_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heater_status_label.setObjectName("heater_status_label")
        self.verticalLayout_5.addWidget(self.heater_status_label)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.heater_status = QtGui.QLabel(self.frame4)
        self.heater_status.setMinimumSize(QtCore.QSize(73, 20))
        self.heater_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heater_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.heater_status.setBaseSize(QtCore.QSize(11, 0))
        self.heater_status.setTextFormat(QtCore.Qt.AutoText)
        self.heater_status.setScaledContents(True)
        self.heater_status.setAlignment(QtCore.Qt.AlignCenter)
        self.heater_status.setObjectName("heater_status")
        self.horizontalLayout_5.addWidget(self.heater_status)
        self.heater_mode = QtGui.QLabel(self.frame4)
        self.heater_mode.setMinimumSize(QtCore.QSize(73, 20))
        self.heater_mode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.heater_mode.setSizeIncrement(QtCore.QSize(0, 0))
        self.heater_mode.setBaseSize(QtCore.QSize(11, 0))
        self.heater_mode.setTextFormat(QtCore.Qt.AutoText)
        self.heater_mode.setScaledContents(True)
        self.heater_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.heater_mode.setObjectName("heater_mode")
        self.horizontalLayout_5.addWidget(self.heater_mode)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.frame4)
        spacerItem8 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem8)
        self.frame5 = QtGui.QFrame(self.frame3)
        self.frame5.setFrameShape(QtGui.QFrame.Box)
        self.frame5.setObjectName("frame5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fan_status_label = QtGui.QLabel(self.frame5)
        self.fan_status_label.setMinimumSize(QtCore.QSize(73, 20))
        self.fan_status_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fan_status_label.setSizeIncrement(QtCore.QSize(0, 0))
        self.fan_status_label.setBaseSize(QtCore.QSize(11, 0))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setUnderline(False)
        font.setBold(True)
        self.fan_status_label.setFont(font)
        self.fan_status_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fan_status_label.setTextFormat(QtCore.Qt.AutoText)
        self.fan_status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fan_status_label.setObjectName("fan_status_label")
        self.verticalLayout_3.addWidget(self.fan_status_label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fan_status = QtGui.QLabel(self.frame5)
        self.fan_status.setMinimumSize(QtCore.QSize(73, 20))
        self.fan_status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fan_status.setSizeIncrement(QtCore.QSize(0, 0))
        self.fan_status.setBaseSize(QtCore.QSize(11, 0))
        self.fan_status.setTextFormat(QtCore.Qt.AutoText)
        self.fan_status.setScaledContents(True)
        self.fan_status.setAlignment(QtCore.Qt.AlignCenter)
        self.fan_status.setObjectName("fan_status")
        self.horizontalLayout_4.addWidget(self.fan_status)
        self.fan_mode = QtGui.QLabel(self.frame5)
        self.fan_mode.setMinimumSize(QtCore.QSize(73, 20))
        self.fan_mode.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.fan_mode.setSizeIncrement(QtCore.QSize(0, 0))
        self.fan_mode.setBaseSize(QtCore.QSize(11, 0))
        self.fan_mode.setTextFormat(QtCore.Qt.AutoText)
        self.fan_mode.setScaledContents(True)
        self.fan_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.fan_mode.setObjectName("fan_mode")
        self.horizontalLayout_4.addWidget(self.fan_mode)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_6.addWidget(self.frame5)
        self.verticalLayout_9.addWidget(self.frame3)
        spacerItem9 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        spacerItem10 = QtGui.QSpacerItem(13, 13, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        DisplayMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(DisplayMainWindow)
        self.statusbar.setObjectName("statusbar")
        DisplayMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(DisplayMainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DisplayMainWindow)

    def retranslateUi(self, DisplayMainWindow):
        DisplayMainWindow.setWindowTitle(QtGui.QApplication.translate("DisplayMainWindow", "Flow Climate Control Display", None, QtGui.QApplication.UnicodeUTF8))
        self.temperature_threshold_label_tab.setText(QtGui.QApplication.translate("DisplayMainWindow", "Temperature Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.temperature_label_tab.setText(QtGui.QApplication.translate("DisplayMainWindow", "Current Temperature:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.temperature_tab), QtGui.QApplication.translate("DisplayMainWindow", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.humidity_threshold_label_tab.setText(QtGui.QApplication.translate("DisplayMainWindow", "Humidity Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.humidity_label_tab.setText(QtGui.QApplication.translate("DisplayMainWindow", "Current Humidity:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.humidity_tab), QtGui.QApplication.translate("DisplayMainWindow", "Humidity", None, QtGui.QApplication.UnicodeUTF8))
        self.connection_status_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Connection status", None, QtGui.QApplication.UnicodeUTF8))
        self.connection_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.latency_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Latency", None, QtGui.QApplication.UnicodeUTF8))
        self.latency.setText(QtGui.QApplication.translate("DisplayMainWindow", "0.0 sec", None, QtGui.QApplication.UnicodeUTF8))
        self.controller_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Controller: ", None, QtGui.QApplication.UnicodeUTF8))
        self.sensor_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Sensor:", None, QtGui.QApplication.UnicodeUTF8))
        self.actuator_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Actuator:", None, QtGui.QApplication.UnicodeUTF8))
        self.controller_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.sensor_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.actuator_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.heater_status_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Heater", None, QtGui.QApplication.UnicodeUTF8))
        self.heater_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.heater_mode.setText(QtGui.QApplication.translate("DisplayMainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.fan_status_label.setText(QtGui.QApplication.translate("DisplayMainWindow", "Fan", None, QtGui.QApplication.UnicodeUTF8))
        self.fan_status.setText(QtGui.QApplication.translate("DisplayMainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.fan_mode.setText(QtGui.QApplication.translate("DisplayMainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))

import resource_rc
